<a href="https://colab.research.google.com/github/VishwakarmaMithun/Python-Inteview/blob/main/Python_Numpy_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [5]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [6]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [7]:
np.linspace(0,10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [8]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [9]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [10]:
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [11]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
np.random.rand(5,2)

array([[0.99937264, 0.19585545],
       [0.04542034, 0.59796836],
       [0.06403185, 0.22072957],
       [0.07475785, 0.88260013],
       [0.36132209, 0.40145196]])

In [13]:
np.random.rand(1)

array([0.1210556])

In [14]:
np.random.rand(5,6)

array([[0.91256651, 0.27374487, 0.19172505, 0.8572999 , 0.4112116 ,
        0.57120392],
       [0.71030112, 0.00801287, 0.70739175, 0.89274778, 0.71920559,
        0.15587201],
       [0.54111822, 0.47130955, 0.14115491, 0.08511888, 0.96267852,
        0.35820242],
       [0.44465949, 0.52630382, 0.38486153, 0.23927019, 0.10129372,
        0.38672083],
       [0.08440305, 0.9434048 , 0.97025607, 0.43005712, 0.64321116,
        0.40307648]])

In [15]:
np.random.rand(5,2)

array([[0.41113275, 0.68315693],
       [0.42617014, 0.11930335],
       [0.92101007, 0.46151657],
       [0.65326885, 0.16667334],
       [0.09571601, 0.33270752]])

In [16]:
np.random.randn(10)

array([-1.32877790e+00,  3.60087537e-01,  6.86325017e-01, -1.06232430e+00,
       -4.29573870e-04, -8.89564553e-01, -1.99669562e+00,  9.53020898e-01,
        1.43039264e-01, -1.78801556e-01])

In [17]:
np.random.randn(2,3)

array([[-0.49289355,  0.34404495, -0.60831793],
       [-0.08308602,  0.82648383,  0.2919072 ]])

In [20]:
np.random.randint(0,101,(4,5))

array([[ 56,  39,  32,  27,  37],
       [ 78,  97,  19,  46,  40],
       [  8,  11,  53,  74, 100],
       [ 10,  68,  83,  86,  78]])

In [21]:
np.random.seed(101)

In [22]:
np.random.rand(4)

array([0.51639863, 0.57066759, 0.02847423, 0.17152166])

In [23]:
arr = np.arange(0,25)

In [25]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [28]:
ranarr = np.random.randint(0,101,10)

In [29]:
ranarr

array([ 9, 77, 40,  4, 63, 40, 60, 92, 64,  5])

In [30]:
ranarr.dtype

dtype('int64')